subtitle: What we do
title: We provide HR Services that will minimise risk and maximise sustainability
body: >-
  As a business owner or senior manager, I’m sure you understand that your most
  valuable asset is your people.  Do you have difficulty sourcing quality
  candidates that not only share your values, but also have the right skills and
  experience to help your business succeed?  Perhaps you’ve considered
  outsourcing human resources in the past but don’t know where to start.  At
  Five Star HR we will partner with you to help create and develop HR practices
  and strategies that will nurture, retain and motivate your employees as well
  as ensure that your business remains compliant with the ever-changing
  employment and Work Health and Safety legislation.  We will provide HR
  consultancy services based on your needs and help you become a Five Star
  employer.
services:
  - title: Adhoc HR Advice and Support
    body: >-
      Depending on your size, outsourcing human resources could cost you as
      little as $165 per month and we will help you resolve your people issues
      simply and quickly. We will provide phone and email support and answer all
      your employee related questions in relation to employment legislation and
      compliance and offer practical advice and solutions to all your staffing
      issues.
  - title: Outsourced HR Manager & Coach
    body: >-
      We can become your dedicated HR Manager (working onsite with your team on
      a regular scheduled basis – 1 day a week, month or fortnight) and look
      after all your HR responsibilities or we can offer a blended approach by
      coaching one of your existing staff members to take on the day-to-day HR
      activities, while we continue to provide strategic HR support.
  - title: HR Project Manager
    body: >-
      Perhaps you just need help on a short-term basis to manage a project, such
      as implement an online HRS or WHS system, support a restructure and
      redundancy process, or cover a long-term absence within your HR team. We
      can provide additional short-term support and HR expertise within your
      business.
other: >-
  # We provide services that are relevant to your needs


  The following Programs are our most popular HR services delivered to
  businesses throughout Sydney, coupled with ongoing support and coaching:


  1. **HR Audits** - using a planned approach we review your current HR
  practice, objectively identify issues, risks and opportunities within the
  business, and develop a 3, 6 or 12 month’ HR Plan for the business.

  2. **HR Compliance Program** - develop compliant employment contracts, new
  hire packs, onboarding and offboarding checklists, and HR policies and
  Procedures.

  3. **HR Skills Coaching** - to assist in building internal HR capability to
  manage day-to-day HR processes for administrators and managers.

  4. **Online HRIS** - implement a comprehensive, online core HRIS solution that
  streamlines, automates and simplifies HR processes (including recruitment,
  onboarding, offboarding, records management, leave management, performance
  management and training management)

  5. **In-house Recruiter** - Partner with the business to provide an end-to-end
  recruitment and selection service (without attracting expensive commissions).
